### ISSUE TITLE
Rail, matplotlib version issue?

### ISSUE THREAD

**Issue by ajw278** [andizq/discminer#1]
Hi Andrés,

I've had some (small) bugs with the analysis tools for discminer. Although they're only small, and I've implemented temporary fixes, it would be great if you could sort them soon so that when I download the updated versions I don't lose my fixes. When using plot_radial_profiles, I get:

Traceback (most recent call last):
  File "/home/awinter/discminer_analysis/mwc758_12co/../_mining/plot_radial_profiles.py", line 207, in <module>
    vel_z, vel_z_error = rail_vz.get_average(**kw_avg)
  File "/home/awinter/anaconda3/lib/python3.10/site-packages/discminer-0.2.6-py3.10.egg/discminer/rail.py", line 328, in get_average
    self.prop_along_coords(**kwargs_along_coords)
  File "/home/awinter/anaconda3/lib/python3.10/site-packages/discminer-0.2.6-py3.10.egg/discminer/rail.py", line 301, in prop_along_coords
    if isinstance(ax2, matplotlib.axes._subplots.Axes): 
AttributeError: module 'matplotlib.axes' has no attribute '_subplots'. Did you mean: 'Subplot'?

I matplotlib.axes doesn't have a _subplots property.. I'm not sure if this is a version issue? I have fixed this by just checking if 'ax2' is a list. 

There was also a separate issue when calling 'prop_along_coords', where keyword arguments sent to were propagated to this via the 'get_average' function, which resulted in an 'unexpected keyword' error. I have hacked a fix for this by adding **kwargs  into the accepted arguments for prop_along_coords. 

Sorry, I know this stuff is small, but hopefully won't take too much time! 

Cheers,
Andrew

**Comment by ajw278** [comment]
PS. Also 'from utils import add_parser_args' should be added to the top of make_double_moments.py I believe...

**Comment by andizq** [comment]
Thanks for sharing Andrew! 

The first bug is indeed a version issue relevant to matplotlib>3.4, and is now fixed on https://github.com/andizq/discminer/commit/d2b60df76334233c6f9348b6cde393e5a48b75f8. 

The other bug is related to new features added recently into the rail.get_average function which require discminer>0.2.8.

As for the parser_args in make_double_moments.py, note that the command line arguments passed to that script have naming conflicts with other arguments more widely used by the other analysis scripts, so I am keeping them separate from those defined in utils.py for now. In the next update I'll resolve those conflicts and redefine everything accordingly so that we can always refer to the arguments listed in utils.add_parser_args.
